In [109]:
import pandas as pd
import numpy as np

df = pd.read_csv("cleaned_data.csv")
df.head()

,TIMESTAMP,PROJECT_NAME,PM2.5,PM10,TEMPERATURE,HUMIDITY
0,2025-12-01 00:00:24+05:30,Jet Speed Real Tors,85.00,141.00,24.6,61.6
1,2025-12-01 00:00:54+05:30,Jet Speed Real Tors,84.50,143.00,24.6,61.4
2,2025-12-01 00:01:24+05:30,Jet Speed Real Tors,84.67,143.67,24.5,61.3
3,2025-12-01 00:01:54+05:30,Jet Speed Real Tors,83.00,143.67,24.5,61.8
4,2025-12-01 00:02:24+05:30,Jet Speed Real Tors,84.33,143.00,24.6,62.4

In [110]:
#Converting from timestamp to datetime
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed')

In [111]:
#Set Index
df = df.set_index('TIMESTAMP')

In [112]:
#Resample data into 1hour batch
sensor_df = df.resample('1h').mean(numeric_only=True)

In [113]:
#Checking  Type of Index
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [114]:
#Interpolate: to replace with mode value of any  columns
sensor_df = sensor_df.interpolate(limit_direction='forward')

In [115]:
#Round-Of Data
sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']] = sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']].round(2)

In [116]:
#Reset Index
sensor_df = sensor_df.reset_index()

In [118]:
sensor_df.head()

                  TIMESTAMP  PM2.5    PM10  TEMPERATURE  HUMIDITY
0 2025-12-01 00:00:00+05:30  92.01  156.11        24.35     63.19
1 2025-12-01 01:00:00+05:30  96.57  164.55        24.24     62.70
2 2025-12-01 02:00:00+05:30  82.28  141.13        23.95     61.23
3 2025-12-01 03:00:00+05:30  75.19  129.93        23.50     61.03
4 2025-12-01 04:00:00+05:30  79.08  135.16        23.42     59.54

Weather Data

In [119]:
#Weather Data 
weather_df = pd.read_excel("C:/Users/admin/Downloads/kherbadi_bandra.xlsx", header=16)
weather_df

,From Date,To Date,Ozone,RH,WS,WD,SR,RF,AT
0,01-12-2025 00:00,01-12-2025 01:00,1.20,60.63,0.96,145.86,0.00,0.0,23.32
1,01-12-2025 01:00,01-12-2025 02:00,1.85,56.44,1.01,98.04,0.00,0.0,23.97
2,01-12-2025 02:00,01-12-2025 03:00,2.23,57.06,0.84,104.93,0.00,0.0,23.27
3,01-12-2025 03:00,01-12-2025 04:00,2.25,56.80,0.72,85.60,0.00,0.0,22.61
4,01-12-2025 04:00,01-12-2025 05:00,0.93,56.16,0.57,138.53,0.00,0.0,22.31
...,...,...,...,...,...,...,...,...,...
2744,25-03-2026 08:00,25-03-2026 09:00,2.08,60.69,0.24,224.96,259.07,0.0,30.91
2745,25-03-2026 09:00,25-03-2026 10:00,11.70,51.67,0.66,289.12,451.88,0.0,32.85
2746,25-03-2026 10:00,25-03-2026 11:00,20.35,53.74,1.17,275.96,613.07,0.0,33.78
2747,25-03-2026 11:00,25-03-2026 12:00,25.45,57.96,1.34,279.95,682.40,0.0,33.76
2748,25-03-2026 12:00,25-03-2026 12:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
#Remode To Date Columns
weather_df = weather_df.drop('To Date',axis=1)

In [121]:
weather_df.set_index('From Date')

                  Ozone     RH    WS      WD      SR   RF     AT
From Date
01-12-2025 00:00   1.20  60.63  0.96  145.86    0.00  0.0  23.32
01-12-2025 01:00   1.85  56.44  1.01   98.04    0.00  0.0  23.97
01-12-2025 02:00   2.23  57.06  0.84  104.93    0.00  0.0  23.27
01-12-2025 03:00   2.25  56.80  0.72   85.60    0.00  0.0  22.61
01-12-2025 04:00   0.93  56.16  0.57  138.53    0.00  0.0  22.31
...                 ...    ...   ...     ...     ...  ...    ...
25-03-2026 08:00   2.08  60.69  0.24  224.96  259.07  0.0  30.91
25-03-2026 09:00  11.70  51.67  0.66  289.12  451.88  0.0  32.85
25-03-2026 10:00  20.35  53.74  1.17  275.96  613.07  0.0  33.78
25-03-2026 11:00  25.45  57.96  1.34  279.95  682.40  0.0  33.76
25-03-2026 12:00    NaN    NaN   NaN     NaN     NaN  NaN    NaN

[2749 rows x 7 columns]

In [122]:
#Replace From Date to TIMESTAMP
weather_df.rename(columns={'From Date':'TIMESTAMP'}, inplace=True)

In [123]:
weather_df = weather_df.set_index('TIMESTAMP')

In [124]:
#Making Timestamp same
sensor_df['TIMESTAMP'] = sensor_df['TIMESTAMP'].dt.tz_localize(None)
#print(sensor_df.columns)
#sensor_df.head()

In [125]:
print(weather_df.columns)

Index(['Ozone', 'RH', 'WS', 'WD', 'SR', 'RF', 'AT'], dtype='object')

In [126]:
weather_df.tail()

                  Ozone     RH    WS      WD      SR   RF     AT
TIMESTAMP
25-03-2026 08:00   2.08  60.69  0.24  224.96  259.07  0.0  30.91
25-03-2026 09:00  11.70  51.67  0.66  289.12  451.88  0.0  32.85
25-03-2026 10:00  20.35  53.74  1.17  275.96  613.07  0.0  33.78
25-03-2026 11:00  25.45  57.96  1.34  279.95  682.40  0.0  33.76
25-03-2026 12:00    NaN    NaN   NaN     NaN     NaN  NaN    NaN

In [127]:
weather_df = weather_df.reset_index()

In [128]:
weather_df['TIMESTAMP'] = pd.to_datetime(
    weather_df['TIMESTAMP'],
    format='%d-%m-%Y %H:%M'
)

In [129]:
weather_df.head()

            TIMESTAMP  Ozone     RH    WS      WD   SR   RF     AT
0 2025-12-01 00:00:00   1.20  60.63  0.96  145.86  0.0  0.0  23.32
1 2025-12-01 01:00:00   1.85  56.44  1.01   98.04  0.0  0.0  23.97
2 2025-12-01 02:00:00   2.23  57.06  0.84  104.93  0.0  0.0  23.27
3 2025-12-01 03:00:00   2.25  56.80  0.72   85.60  0.0  0.0  22.61
4 2025-12-01 04:00:00   0.93  56.16  0.57  138.53  0.0  0.0  22.31

In [130]:
#weather_df = weather_df.drop('Ozone',axis=1)

In [131]:
weather_df.head()

            TIMESTAMP  Ozone     RH    WS      WD   SR   RF     AT
0 2025-12-01 00:00:00   1.20  60.63  0.96  145.86  0.0  0.0  23.32
1 2025-12-01 01:00:00   1.85  56.44  1.01   98.04  0.0  0.0  23.97
2 2025-12-01 02:00:00   2.23  57.06  0.84  104.93  0.0  0.0  23.27
3 2025-12-01 03:00:00   2.25  56.80  0.72   85.60  0.0  0.0  22.61
4 2025-12-01 04:00:00   0.93  56.16  0.57  138.53  0.0  0.0  22.31

In [132]:
#Merge Data So our ML model can train
merged_df = pd.merge(sensor_df,weather_df, on="TIMESTAMP")

In [133]:
merged_df = merged_df.dropna()

In [134]:
merged_df.size

31032

In [152]:
print(merged_df.columns)

Index(['TIMESTAMP', 'PM2.5', 'PM10', 'TEMPERATURE', 'HUMIDITY', 'Ozone', 'RH',
       'WS', 'WD', 'SR', 'RF', 'AT'],
      dtype='object')

LSTM PREDICTION MODEL (72 HOURS PAST DATA - 24 HOURS FUTURE PREDICTION)

In [135]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [136]:
#Select Features
features = [
    'PM2.5', 'PM10', 'TEMPERATURE', 'HUMIDITY',
    'WS', 'WD', 'RF', 'Ozone'
]

data = merged_df[features]

In [137]:
#Normalize Data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

In [138]:
#Create Sequence
def create_sequences(data, window=72, horizon=24):
    X, y = [], []
    
    for i in range(len(data) - window - horizon):
        X.append(data[i:i+window])
        y.append(data[i+window:i+window+horizon, 0:2])  # PM2.5, PM10
    
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data)

In [139]:
#Train-Test Split
split = int(len(X) * 0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

In [140]:
#Build LSTM Model
from tensorflow.keras.layers import Input

model = Sequential([
    Input(shape=(72, X.shape[2])),

    LSTM(128, return_sequences=True),
    Dropout(0.2),

    LSTM(64),
    Dropout(0.2),

    Dense(32, activation='relu'),
    Dense(48)
])

In [141]:
#Compile Model
model.compile(
    optimizer='adam',
    loss='mse'
)

In [142]:
#Train Model
model.fit(
    X_train,
    y_train.reshape(y_train.shape[0], -1),
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test.reshape(y_test.shape[0], -1))
)

Epoch 1/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0468 - val_loss: 0.0250
Epoch 2/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 63ms/step - loss: 0.0128 - val_loss: 0.0193
Epoch 3/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.0108 - val_loss: 0.0204
Epoch 4/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 60ms/step - loss: 0.0100 - val_loss: 0.0184
Epoch 5/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 62ms/step - loss: 0.0089 - val_loss: 0.0178
Epoch 6/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.0080 - val_loss: 0.0191
Epoch 7/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 68ms/step - loss: 0.0077 - val_loss: 0.0200
Epoch 8/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 69ms/step - loss: 0.0073 - val_loss: 0.0196
Epoch 9/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 5s 62ms/step - loss: 0.0068 - val_loss: 0.0203
Epoch 10/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 69ms/step - loss: 0.0065 - val_loss: 0.0241
Epoch 11/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.0067 - val_loss: 0.0181
Epoch 12/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.0064 - val_loss: 0.0193
Epoch 13/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 67ms/step - loss: 0.0060 - val_loss: 0.0189
Epoch 14/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 5s 73ms/step - loss: 0.0059 - val_loss: 0.0181
Epoch 15/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0056 - val_loss: 0.0194
Epoch 16/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0056 - val_loss: 0.0186
Epoch 17/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 5s 75ms/step - loss: 0.0055 - val_loss: 0.0208
Epoch 18/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 0.0052 - val_loss: 0.0198
Epoch 19/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 9s 66ms/step - loss: 0.0051 - val_loss: 0.0218
Epoch 20/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0049 - val_loss: 0.0223

In [143]:
#Predict
pred = model.predict(X_test)

# reshape back to (samples, 24, 2)
pred = pred.reshape(-1, 24, 2)
y_test = y_test.reshape(-1, 24, 2)

16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step

In [144]:
#Evaluate
mae_pm25 = mean_absolute_error(y_test[:,:,0].flatten(), pred[:,:,0].flatten())
mae_pm10 = mean_absolute_error(y_test[:,:,1].flatten(), pred[:,:,1].flatten())

print("PM2.5 MAE:", mae_pm25)
print("PM10 MAE:", mae_pm10)

PM2.5 MAE: 0.11657230279291454
PM10 MAE: 0.09607245831800691

In [145]:
#Convert to Work/Not
PM25_LIMIT = 100
PM10_LIMIT = 250

def decision(pm25, pm10):
    return 0 if (pm25 > PM25_LIMIT or pm10 > PM10_LIMIT) else 1

In [146]:
#Decision Accuracy
actual = []
predicted = []

for i in range(len(pred)):
    for t in range(24):
        actual.append(decision(y_test[i, t, 0], y_test[i, t, 1]))
        predicted.append(decision(pred[i, t, 0], pred[i, t, 1]))

from sklearn.metrics import accuracy_score, classification_report

print("Decision Accuracy:", accuracy_score(actual, predicted))
print(classification_report(actual, predicted))

Decision Accuracy: 1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     11952

    accuracy                           1.00     11952
   macro avg       1.00      1.00      1.00     11952
weighted avg       1.00      1.00      1.00     11952

In [147]:
#Real-Time Prediction
# Take last 72 hours
last_72 = scaled_data[-72:]

# reshape for model
last_72 = last_72.reshape(1, 72, X.shape[2])

future = model.predict(last_72)

future = future.reshape(24, 2)

# Example: next day average PM
pm25_next = future[:,0].mean()
pm10_next = future[:,1].mean()

print("Tomorrow Avg PM2.5:", pm25_next)
print("Tomorrow Avg PM10:", pm10_next)

if decision(pm25_next, pm10_next):
    print("✅ CONTINUE WORK")
else:
    print("❌ STOP WORK")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
Tomorrow Avg PM2.5: 0.14390105
Tomorrow Avg PM10: 0.12203077
✅ CONTINUE WORK

In [148]:
# Save full model
model.save("lstm_model3.h5")

# Save scaler (VERY IMPORTANT)
import joblib
joblib.dump(scaler, "scaler3.pkl")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

['scaler3.pkl']

In [149]:
merged_df.to_csv("merged_df3.csv", index=False)

In [150]:
import os
print(os.getcwd())

C:\Users\admin\Site_Work_Prediction_ML_Model

In [151]:
print(os.listdir())

['.git', '.ipynb_checkpoints', '24March Data Resample.ipynb', 'app.py', 'cleaned_data.csv', 'Future Prediction Model.ipynb', 'lstm_model.h5', 'lstm_model2.h5', 'lstm_model3.h5', 'merged_df.csv', 'merged_df2.csv', 'merged_df3.csv', 'Predicting site with anomalies data.ipynb', 'Predicting with Jet Speed Data.ipynb', 'README.md', 'requirements.txt', 'scaler.pkl', 'scaler2.pkl', 'scaler3.pkl', 'Untitled.ipynb']